AspNetWeb2/Models/Album.cs
namespace AspNetWeb2.Models
{
    public class Album
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public DateTime? ReleaseDate{ get; set; }
    }
}

AspNetWeb2/Models/ErrorViewModel.cs
namespace AspNetWeb2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AspNetWeb2/Controllers/MusicController.cs
using AspNetWeb2.Models;
using Microsoft.AspNetCore.Mvc;


namespace AspNetWeb2.Controllers
{
    public class MusicController : Controller
    {
        private static readonly List<Album> _albums = new List<Album>
        {
            new Album
            {
            Id = 1,
            Name = "...And Justice for All",
            ReleaseDate = new DateTime(1988, 8, 25)
            },
            new Album
            {
            Id = 2,
            Name = "Hardwired... to Self-Destruct",
            ReleaseDate = new DateTime(2016, 11, 18)
            }
        };

       
        [HttpGet("/")]
        public IActionResult Index()
        {
            return Json(_albums);
        }

        [HttpPost("albums/add")]
        public IActionResult AddAlbum(Album album)
        {
            var newId=_albums.Max(i=>i.Id)+1;
            album.Id = newId;
            _albums.Add(album);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost("albums/delete/{id?}")]
        public IActionResult DeleteAlbum(int id)
        {
            var album = _albums.FirstOrDefault(x => x.Id == id);
            if (album == null)
            {
                NotFound();
            }
            _albums.Remove(album!);
            return RedirectToAction("Index");
        }
        [HttpPost("albums/edit")]
        public IActionResult EditAlbum(Album editableAlbum)
        {
            var index = _albums.FindIndex(album => album.Id == editableAlbum.Id);
            _albums[index] = editableAlbum;
            return RedirectToAction("Index");
        }

    }
}

AspNetWeb2/Views/Music/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AspNetWeb2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetWeb2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspNetWeb2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Music" asp-action="Index">AspNetWeb2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Music" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Music" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AspNetWeb2 - <a asp-area="" asp-controller="Music" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>